[test]
preload = ["./tests/__preload__/svelteLoader.ts", "./tests/__preload__/happydom.ts", "./tests/__preload__/obsidianMock.ts"]
root = "./tests"
coverage = true
coverageReporter = ["text"]
coveragePathIgnorePatterns = ["tests/__preload__/*"]